# Generated by Django 4.2.3 on 2023-07-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museumtual', '0007_cart_remove_type_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='name',
        ),
        migrations.AddField(
            model_name='cart',
            name='museum_choice',
            field=models.CharField(choices=[('acropolis', 'Acropolis')], default='other', max_length=100),
        ),
    ]
