# Generated by Django 4.2.3 on 2023-07-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museumtual', '0008_remove_cart_name_cart_museum_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='museum_choice',
            field=models.CharField(choices=[(' ', ' '), ('acropolis', 'Acropolis'), ('saudi', 'Saudi'), ('harvard', 'Harvard')], default='other', max_length=100),
        ),
    ]
