# Generated by Django 4.2.3 on 2023-07-25 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('museumtual', '0012_alter_museum_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museum',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='museumuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
