# Generated by Django 4.2.3 on 2023-07-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museumtual', '0013_alter_museum_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museum',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
